name: EMRA For OriginOS

on:
  workflow_dispatch:
    inputs:
      device:
        description: "设备类型"
        required: true
        type: choice
        options:
        - Phone
        - Pad
        - Fold
      link:
        description: 'ROM 链接'
        required: true
      devicename:
        description: '设备名'
        required: false
      osversion:
        description: '系统版本'
        required: false

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Maximizing storage
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 4096
        temp-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependence
      run: |
        pip install -r requirements.txt

    - name: Download extract.erofs
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "sekaiacg/erofs-utils"
        latest: true
        extract: true
        fileName: 'erofs-utils-*-Linux_x86_64-*.zip'

    - name: Download payload-dumper-go
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "ssut/payload-dumper-go"
        latest: true
        extract: true
        fileName: 'payload-dumper-go_*_linux_amd64.tar.gz'

    - name: Remove file
      run: |
       rm *.tar.gz *.zip

    - name: Download ROM
      run: |
        python main.py -d ${{ github.event.inputs.link }}

    - name: Switch device type
      run: |
        if [ "${{ github.event.inputs.device }}" = "Phone" ]; then
            python main.py -t 0 ph
          elif [ "${{ github.event.inputs.device }}" = "Pad" ]; then
            python main.py -t 0 p
          elif [ "${{ github.event.inputs.device }}" = "Fold" ]; then
            python main.py -t 0 f
          else
            echo "Invalid device specified."
            exit 1
          fi

    - name: Unzip payload.bin
      run: |
        python main.py -p
        rm *.zip

    - name: Unzip img
      run: |
        python main.py -i
        rm payload.bin
    
    - name: Unzip file
      run: |
        ./extract.erofs -i system.img -x -T8
        rm *.img

    - name: Remove exclude apk
      run: |
        python main.py -a

    - name: Get version
      run: |
        python main.py -n

    - name: Update database
      run: |
        python main.py -u

    - name: Rename
      run: |
        python main.py -m

    - name: Upload json
      uses: actions/upload-artifact@v4
      with:
        name: Update_json
        path: |
          app_version.json
          app_code.json
    
    - name: Upload update_apk
      uses: actions/upload-artifact@v4
      with:
        name: Update_apk
        path: |
          update_apk
          update_name_apk

    - name: Update database
      run: |
        python main.py -t 1 ph
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "${GITHUB_ACTOR}"
        if [ "${{ github.event.inputs.device }}" = "Phone" ]; then
            git add phone/
          elif [ "${{ github.event.inputs.device }}" = "Pad" ]; then
            git add pad/
          elif [ "${{ github.event.inputs.device }}" = "Fold" ]; then
            git add fold/
          else
            echo "Unknown device type."
            exit 1
          fi
        git commit -m "Upload Database ${{ github.event.inputs.devicename }} ${{ github.event.inputs.osversion }}"
        git push origin main
